### PR TITLE
fix: avoid race condition `facilitiesStore.ts`

### LINKED ISSUE #1186: Make update of `healthProfessionalsRelations` atomic to prevent ESLint warning
# Problem
The data in the `facilitySectionFields.healthProfessionalsRelations` array might be updated slowly or from different parts of the app. If `updateFacility()` runs before this data finishes updating, it might use an old or incomplete version of it. This can cause healthcare professionals that should be connected to a facility to be missed or saved incorrectly.

Image

# Success
The array of relationships has to be built safely without any potential race condition issues.

### Requirements

- [ ] Avoid reading and writing `facilitySectionFields.healthProfessionalsRelations` in the same async scope.

### PR DESCRIPTION
**Pull request by ljbroersen**
✅ Resolves #1186 
- [x] PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specifications
- [x] PR assignee has been selected
- [x] PR label has been selected
- [x] @NabbeunNabi has been selected for preliminary review

## 🔧 What changed
This PR updates the logic inside the `updateFacility()` function to unconditionally clear `facilitySectionFields.healthProfessionalsRelations` after a successful facility update.

By resetting the array once the update is confirmed, the code avoids potential race conditions and ensures a clean state for the next user interaction.

### CODE REVIEW

**Review by NabbeunNabi — CHANGES_REQUESTED** [review]
This field is non existent on a facility for our types. We only use it on the frontend to track if users pick a HP to add or remove from a facility. Is there a way to guarantee that it is set back to an empty array when no errors come back and remove this race condition. I am not quite sure how this will consistently clear the array.

You can see [here](https://github.com/ourjapanlife/findadoc-web/blob/85aecf5db3f9e39dcbd66e483549af7cd91a3595/typedefs/gqlTypes.ts#L106) that is is only a type on the frontend we add but not part of the response or anything from the backend. We just want to make sure the relationships we send back are cleared.

So these relationships are calculated based on the healthcare professional ids and if we add or remove them we create these relations within the array to send to the backend. Once we get a response back without errors we need to always clear the array

You can see it is necessary in the [mutation](https://github.com/ourjapanlife/findadoc-web/blob/85aecf5db3f9e39dcbd66e483549af7cd91a3595/typedefs/gqlTypes.ts#L493) though and that is why we create it.

Maybe I do not understand exactly what your function is doing?

**Comment by NabbeunNabi** [comment]
@ljbroersen have you updated this? If so don't hesitate to ping me for re review. If you haven't then kindly disregard until addressed

File: stores/facilitiesStore.ts [hunk 1]
```diff
@@ -209,11 +211,20 @@ export const useFacilitiesStore = defineStore(
...
+
+                // compare the healthProfessionalRelations array from before and after updating the facility
+                const postUpdateRelations = facilitySectionFields.healthProfessionalsRelations
+                const hasUserChangedRelations
+                    = postUpdateRelations.length !== preUpdateRelations.length
+                      || !postUpdateRelations.every((relation, i) => relation === preUpdateRelations[i])
+
+                if (!hasUserChangedRelations) {
+                    facilitySectionFields.healthProfessionalsRelations = []
+                }
```
Comment (NabbeunNabi) [inline stores/facilitiesStore.ts:227]: This is where my confusion is for reference

**Review by NabbeunNabi — APPROVED** [review]
@ermish time
