### PR TITLE
fix: reduce method only runs when submissions are present

### LINKED ISSUE #1238: bug: moderation dashboard not loading when backtracking from create or edit pages
# Problem
When navigating back from a create or edit page in moderation this error appears in the console:

Image

It comes from a function which attempts to sort the submission counts and then display them in the left navbar. When it does this to an empty Submissions array it causes the above error and doesn't allow the page to change back to the moderation dashboard.

# Success
The error no longer appears and navigating back to the dashboard is possible.

# Implementation notes
Only running the function causing the error when the array of Submissions has submissions in it may prevent the error.

### PR DESCRIPTION
**Pull request by ConwayDecker**
✅ Resolves #1238 
- [X] PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specifications
- [X] PR assignee has been selected
- [X] PR label has been selected
- [X] @NabbeunNabi has been selected for preliminary review

## 🔧 What changed
A conditional has been added to the createCountsForSubmissionListView which prevents it from running if the provided array of Submissions is empty. Optional chaining operators and nullish coalescing operators have also been added to where the sorted submission counts appear to prevent potential TypeScript errors or blank spaces if they are undefined.

## 📸 Screenshots

-   ### Before
https://github.com/user-attachments/assets/fde7a1a6-c61c-4fc8-857b-4f6c3aafc0ae

-   ### After
https://github.com/user-attachments/assets/4551b327-445e-4f7e-9a98-8b6cb9685c64

### CODE REVIEW

File: components/ModDashboardLeftNavbar.vue [hunk 1]
```diff
@@ -94,26 +94,28 @@ const updateSelectedDashboardView = (event: Event) => {
...
-        if (isNewSubmission) {
-            statusCountObject.forReviewCount += 1
-        }
-        return statusCountObject
-    }, {
-        forReviewCount: 0,
-        approvedCount: 0,
-        rejectedCount: 0
-    })
+    if (submissions.length > 0) {
```
Comment (NabbeunNabi) [inline components/ModDashboardLeftNavbar.vue:97]: This is a good start! I would think for easier readability and for it to defaulting to the count as that is the behavior we want when there are submissions to just check if there is not a length and if so return. Otherwise return the reduce.

Something like 

```
if (!submissions.length) return 0
```

**Review by NabbeunNabi — CHANGES_REQUESTED** [review]

File: components/ModDashboardLeftNavbar.vue (hunk 1 above)
Comment (ConwayDecker) [reply components/ModDashboardLeftNavbar.vue]: I added `if (!submissions.length) return undefined` instead of returning 0 because the references of `autofillStatusCount` in the template showed a possible error if it returns as 0 (and then tries to access rejectedCount or other properties). With undefined it will default to 0.

Comment (NabbeunNabi) [reply components/ModDashboardLeftNavbar.vue]: Ahhh yes.

I actually meant to remove the 0.

Because you have the default parts up top.

It would need to return that object in the reducer.

Should just be undefined. Nice one

File: components/ModDashboardLeftNavbar.vue [hunk 2]
```diff
@@ -94,6 +94,7 @@ const updateSelectedDashboardView = (event: Event) => {
 }
 
 function createCountsForSubmissionListView(submissions: Submission[]) {
+    if (!submissions.length) return undefined
     return submissions.reduce((statusCountObject, submission) => {
```
Comment (NabbeunNabi) [inline components/ModDashboardLeftNavbar.vue:98]: @ConwayDecker i know this was something I did. But it is more common I have heard from people to set the map or something to a variable such as `countedSubmissions` then return that.

It can make the reduce more readable as to what it actually is instead of returning it directly.

Do you mind doing that here and atoning for past Will's unreadableness

**Review by NabbeunNabi — CHANGES_REQUESTED** [review]

**Review by NabbeunNabi — CHANGES_REQUESTED** [review]
Made a comment about the function. Almost there @ConwayDecker

**Review by theyokohamalife — APPROVED** [review]
Nice! ✨
