### PR TITLE
fix: clicking outside modal closes modal

### LINKED ISSUE #1079: bug: clicking outside the modal should close it
# Problem
When clicking on a result, the modal pops up and clicking outside of it used to close it. Now, it doesn't work. Let's fix it! 

# Success
# Implementation notes
#1077 and #1078 are associated

### PR DESCRIPTION
**Pull request by matthewkurtti**
✅ Resolves #1079 
- [x] PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specifications
- [x] PR assignee has been selected
- [x] PR label has been selected
- [x] @NabbeunNabi has been selected for preliminary review

## 🔧 What changed
 - Took vCloseOnOutsideClick function used in hamburger menu and made it a new utility function that can be used in other files.
 - import that new utility function in hamburger menu and modal and uses it in both

## 🧪 Testing instructions

Try pulling this PR branch and see if you can click outside the modal and hamburger menu to close them

## 📸 Screenshots

-   ### Before

chrome-capture-2025-4-17 (1)

-   ### After

chrome-capture-2025-4-17

https://github.com/user-attachments/assets/99d60104-e113-4574-a5cc-d788b6e02a0b

### CODE REVIEW

File: components/Modal.vue [hunk 1]
```diff
@@ -40,12 +41,19 @@
 </template>
 
 <script lang="ts" setup>
+import { onClickOutside } from '@vueuse/core'
```
Comment (NabbeunNabi) [inline components/Modal.vue:44]: @matthewkurtti This is a good start as to looking, but when we add dependencies, me need to maintain dependencies. We actually have this functionality that we built ourself within the hamburger menu as seen here https://github.com/ourjapanlife/findadoc-web/blob/9904af9819ffaf3c886ba9d7abe3a3f5da8e09b1/components/HamburgerMenu.vue#L311

I would suggest making this a utility function and import it into the hamburger menu and the modal and have it work both places. This way we control the function and do not have another dependency to manage

**Review by NabbeunNabi — CHANGES_REQUESTED** [review]
@matthewkurtti Great start!

File: components/Modal.vue (hunk 1 above)
Comment (matthewkurtti) [reply components/Modal.vue:44]: Sounds good! I'll try using that instead. Ty!

Comment (NabbeunNabi) [reply components/Modal.vue:44]: @matthewkurtti Since you are back to working on this you can move it back to draft and move the issue on the board and this PR back to in progress while working on it 🙇‍♂️

Comment (matthewkurtti) [reply components/Modal.vue]: Instead of using vueuse/core, the latest commit has a util function for closing the modal

**Comment by matthewkurtti** [comment]
The latest commit has a new util function called closeOnOutsideClick.ts in the utils directory. Only other changes were in HamburgerMenu.vue and Modal.vue. In case it's not visible on the commit, @Zugim helped me out a ton with this. Go teamwork.  Please take a look when you get a chance and let us know if you'd like anything else changed. Thank you!

File: utils/closeOnOutsideClick.ts [hunk 2]
```diff
@@ -0,0 +1,28 @@
+import type { DirectiveBinding } from 'vue'
+
+type ElWithOutsideHandler = HTMLElement & {
+    clickOutsideEvent: (event: MouseEvent) => void
+}
+
+//this is a custom directive to close the menu when clicking outside of the menu
```
Comment (NabbeunNabi) [inline utils/closeOnOutsideClick.ts:7]: This comment seems outdated as it is not only for a menu. It would be clicking outside of an open element

File: components/Modal.vue [hunk 3]
```diff
@@ -40,8 +42,11 @@
 </template>
 
 <script lang="ts" setup>
+import { ref } from 'vue'
 import { useModalStore } from '~/stores/modalStore'
+import { vCloseOnOutsideClick } from '#imports'
```
Comment (NabbeunNabi) [inline components/Modal.vue:47]: This needs to be updated in our documentation...but we prefer to import things specifically for the file path if not a `Nuxt` specific import. This helps new developers find exactly where the file is being imported from. For example.  You can look at the like above it. So if you could update the import to something like `'/utils/closeOnOutsideClick'` or add `ts` if necessary.

File: components/HamburgerMenu.vue [hunk 4]
```diff
@@ -264,6 +264,7 @@ import SVGProfileIcon from '~/assets/icons/profile-icon.svg'
 import SVGHamburgerMenuIcon from '~/assets/icons/hamburger-menu.svg'
 import SVGGithubIcon from '~/assets/icons/social-github.svg'
 import { useAuthStore } from '~/stores/authStore'
+import { vCloseOnOutsideClick } from '#imports'
```
Comment (NabbeunNabi) [inline components/HamburgerMenu.vue:267]: ♻️

**Review by NabbeunNabi — APPROVED** [review]
Great job! A couple quick things that I know you can fixup and then it is ready for @theyokohamalife and @ermish

File: utils/closeOnOutsideClick.ts (hunk 2 above)
Comment (matthewkurtti) [reply utils/closeOnOutsideClick.ts]: deleted this outdated comment in latest commit

File: components/Modal.vue (hunk 3 above)
Comment (matthewkurtti) [reply components/Modal.vue]: specified the import path in commit 8cc2ca6

File: components/HamburgerMenu.vue (hunk 4 above)
Comment (matthewkurtti) [reply components/HamburgerMenu.vue]: specified the import path in commit 8cc2ca6

**Comment by matthewkurtti** [comment]
One of the Cypress tests are not passing. I'll move this PR back to draft while investigating.

**Review by theyokohamalife — COMMENTED** [review]
I tried this locally on both Chrome and Firefox, but I was unable to replicate it. 🤔 

https://github.com/user-attachments/assets/e8a7f8e7-f66e-4334-b1d4-1ce8822cd175

**Comment by ermish** [comment]
@matthewkurtti I'll put this is in draft for now, can you check @theyokohamalife 's comment? When it's ready, feel free to put it back in the ready for review state again 😸

**Comment by matthewkurtti** [comment]
Sorry for taking so long to respond to this! I'll start deep diving why it's not working now. Something might have happened after rebasing

**Comment by matthewkurtti** [comment]
This PR is ready for review again!

**Review by ermish — APPROVED** [review]
Looks great! Thanks @matthewkurtti !
