### PR TITLE
fix: add breakpoints to make site usable on mobile

### LINKED ISSUE #347: Map not visible on mobile
When we view the application with a smartphone, the map is not visible anymore and we only see the search result. I think we need something similar like the google map mobile app. When we click on tag it open on full screen the doctor. And have a different page/modal/slide for all search results? (something we should discuss)

Image

# Requirements

- [x] Create a responsive search results and map for mobile

# Dependencies

- None (Add any issue dependencies here)

### PR DESCRIPTION
**Pull request by theyokohamalife**
Resolves #347 

This PR is part of a 🥞

1. https://github.com/ourjapanlife/findadoc-web/pull/352 
2. https://github.com/ourjapanlife/findadoc-web/pull/351 
3. https://github.com/ourjapanlife/findadoc-web/pull/353 👈🏼 You are here

# What changed
Creates different layouts based on whether or not the screen is larger or smaller than a tablet.
See the mobile design on [Figma](https://www.figma.com/file/QXQxlw4jNFIhMxkKU7bbwq/Find-a-doc%2C-Japan?type=design&node-id=704-12700&mode=design).

# Testing instructions
Click the Netlify preview in the comment below, and resize the page to mobile and check that it's responsive.

# Screenshots

## Before
Screenshot 2023-12-31 at 6 21 59 AM

## After
Screenshot 2023-12-31 at 6 21 02 AM

### CODE REVIEW

File: components/TopNav.vue [hunk 1]
```diff
@@ -50,12 +49,20 @@
...
 </template>
 
 <script lang="ts" setup>
 import { useSubmissionStore } from "~/stores/submissionStore";
 import { useMenuStore } from "~/stores/menuStore";
+import { useNuxtApp } from "#app";
+import { watch } from "vue";
+const { $viewport } = useNuxtApp();
+
+watch($viewport.breakpoint, (newBreakpoint, oldBreakpoint) => {
```
Comment (ermish) [inline components/TopNav.vue:63]: Should remove this for production

File: components/TopNav.vue [hunk 2]
```diff
@@ -50,12 +49,20 @@
...
             <LocaleSelector />
         </div>
+        <HamburgerComponent v-else />
     </div>
 </template>
 
 <script lang="ts" setup>
 import { useSubmissionStore } from "~/stores/submissionStore";
 import { useMenuStore } from "~/stores/menuStore";
+import { useNuxtApp } from "#app";
```
Comment (ermish) [inline components/TopNav.vue:59]: I don't think we need this import here

File: nuxt.config.js [hunk 3]
```diff
@@ -96,9 +96,33 @@ export default defineNuxtConfig({
...
+        breakpoints: {
+            desktop: 1024,
+            desktopMedium: 1280,
+            desktopWide: 1600,
+
+            mobile: 320,
+            mobileMedium: 375,
+            mobileWide: 425,
+
+            tablet: 768,
```
Comment (ermish) [inline nuxt.config.js:112]: Instead of a bunch of device breakpoints, what are your thoughts on using "portrait" vs "landscape" orientation only? 

The size doesn't really matter except if it's really small, then you force to portrait mode.

File: pages/index.vue [hunk 4]
```diff
@@ -1,13 +1,36 @@
...
+                <div class="flex flex-col h-full">
+                    <MainContentContainer />
+                </div>
+            </div>
+        </div>
     </div>
 </template>
+
+<script setup lang="ts">
+import { useNuxtApp } from "#app";
```
Comment (ermish) [inline pages/index.vue:26]: Don't think we need this one either

File: pages/index.vue [hunk 5]
```diff
@@ -1,13 +1,36 @@
...
+import { watch } from "vue";
+const { $viewport } = useNuxtApp();
+import { useModalStore } from "~/stores/modalStore";
+
+const store = useModalStore();
+
+watch($viewport.breakpoint, (newBreakpoint, oldBreakpoint) => {
```
Comment (ermish) [inline pages/index.vue:33]: Same here

**Review by ermish — CHANGES_REQUESTED** [review]
Added a few small cleanups

File: components/TopNav.vue (hunk 2 above)
Comment (theyokohamalife) [reply components/TopNav.vue:59]: @ermish It's needed for `$viewport`:

`const { $viewport } = useNuxtApp();`

File: nuxt.config.js (hunk 3 above)
Comment (theyokohamalife) [reply nuxt.config.js:112]: @ermish These are the default values, but I think we need to differentiate at least between tablet and desktop, because tablet is experiencing bugs with the top nav and the map is barely visible.

Either way, I'd like to at least get the mobile site working first, and then nitpick on the custom breakpoints that are being used. Currently, the site is still completely broken for mobile without this PR and I'd like to get it to a usable state.

File: pages/index.vue (hunk 4 above)
Comment (theyokohamalife) [reply pages/index.vue:26]: @ermish See comment above.

File: pages/index.vue (hunk 5 above)
Comment (theyokohamalife) [reply pages/index.vue:33]: @ermish See comment above.

File: nuxt.config.js (hunk 3 above)
Comment (ermish) [reply nuxt.config.js:112]: Yeah we'll need to make it more responsive. Ok we can figure out later.

**Review by ermish — APPROVED** [review]
:shipit:
