### PR TITLE
fix: change locales to send code to backend

### LINKED ISSUE #891: Fix a bug where the submission sends language text instead of code to the backend
# Problem
The languages when formatted set the value of the option to the text that is displayed. We need to show the text, but send the code associated with it since that is the set up of the backend.

# Success
The text is displayed with simple text from the `LocaleDisplayOptions` and the code is sent to the backend so a submission can again be successfully submitted.

### Requirements

- [x] Display the text formatted to be readable for the user
- [x] Set the value of the options to the display code
- [x] Manually test the submission can still be accepted

### PR DESCRIPTION
**Pull request by NabbeunNabi**
Resolves #891 
- [x] PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specs

## 🔧 What changed
There was a bug that when the languages were formatted in an array there was no code, and the backend expects a code. So this has a function that fixes it so we display languages from code to text, and set the option value to the code itself. This allows us to send the correct information to the backend.

1. Fix the display to show text but set `option` value to the code
2. Fix the locales to be set initially to the values of spoken languages submitted
3. Change type button on the copy button to prevent default browser behavior
4. Add function to format a singular language code to simple text in order to display the healthcare professional spoken languages that are submitted
5. Update UI based on function

## 🧪 Testing instructions
Currently while intercept and testing is being built. You need to check out to this branch and run the server by running
```
npm run dev:startlocaldb
npm run dev
```

And then on the frontend run
```
yarn dev:localserver
```

Check the Submission form and try to submit a completed form.
## 📸 Screenshots

-   ### Before
- 
image

-   ### After
image
image
image
image

https://github.com/user-attachments/assets/20333180-3bac-4e20-9b9d-9980bce99728

### CODE REVIEW

File: components/ModEditSubmissionForm.vue [hunk 1]
```diff
@@ -464,11 +471,11 @@
                         text-primary-text text-sm font-normal font-sans placeholder-primary-text-muted"
             >
                 <option
-                    v-for="(locale, index) in formattedLanguages"
-                    :key="`${locale}-${index}`"
-                    :value="locale"
+                    v-for="(locale, index) in localeOptions"
+                    :key="`hp-${locale}-${index}`"
```
Comment (ermish) [inline components/ModEditSubmissionForm.vue:475]: good addition

File: stores/localeStore.ts [hunk 2]
```diff
@@ -9,11 +9,16 @@ export type LocaleDisplay = {
...
     const locale: Ref<LocaleDisplay> = ref(enUsLocale)
 
     function setLocale(selectedLocale: Locale) {
-        locale.value = localeDisplayOptions.find(l => l.code == selectedLocale) as LocaleDisplay
+        locale.value = localeDisplayOptions.find(l => l.code === selectedLocale) as LocaleDisplay
+    }
+
+    function formatLanguageCodeToSimpleText(selectedLocale: string) {
+        const language = localeDisplayOptions.find(locale => locale.code === selectedLocale)
+        return language?.simpleText || 'Language not found'
```
Comment (ermish) [inline stores/localeStore.ts:21]: nit: could be a localized string

File: stores/localeStore.ts [hunk 3]
```diff
@@ -9,11 +9,16 @@ export type LocaleDisplay = {
...
-    const enUsLocale = localeDisplayOptions.find(o => o.code == Locale.EnUs) as LocaleDisplay
+    const enUsLocale = localeDisplayOptions.find(o => o.code === Locale.EnUs) as LocaleDisplay
     const locale: Ref<LocaleDisplay> = ref(enUsLocale)
 
     function setLocale(selectedLocale: Locale) {
-        locale.value = localeDisplayOptions.find(l => l.code == selectedLocale) as LocaleDisplay
+        locale.value = localeDisplayOptions.find(l => l.code === selectedLocale) as LocaleDisplay
+    }
+
+    function formatLanguageCodeToSimpleText(selectedLocale: string) {
```
Comment (ermish) [inline stores/localeStore.ts:19]: we should call this `displayText` or something that better describes when to use it. Maybe it's just me, but I wouldn't know what simple vs complex text is

File: stores/localeStore.ts (hunk 2 above)
Comment (ermish) [inline stores/localeStore.ts:21]: ♻️

File: stores/localeStore.ts (hunk 3 above)
Comment (NabbeunNabi) [reply stores/localeStore.ts:19]: Nuxt compiles the i18n so within the store I still have to figure out how the store can have access to translatable strings
