### PR TITLE
fix: improve submission form ui and ux

### LINKED ISSUE #873: BUG: fix `SubmissionForm.vue` - No loading for stores
# Problem
Currently, the data from the [submit form](https://www.findadoc.jp/submit) is loading without a loading indicator, causing the inputs to reset, resulting in a flickering effect.

# Success
Load the form only after the stores have finished loading.

### Requirements
- [x] Display loading
- [x] The form loads properly

### PR DESCRIPTION
**Pull request by NabbeunNabi**
Resolves #873
- [x] PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specs

## 🔧 What changed

- the `ServerResponse` type was changed to match what is delivered from the `resolvers` from the backend based on the built in graphQLError we must covert our backend to before messaging to the frontend.
- Error toasts and success toasts are displayed to the user on the frontend depending on the submission status
- The api call now uses the built in retry and returns the response where we have access to the submission and to the errors
- Updated `SubmissionForm.vue` to use lifecycle hooks in order to render the form once the refs are loaded within the component
- Component specific refs for the submission were moved to the component and our of the store
- The thank you component has a button to submit another doctor and the forms are conditionally rendered in order to remount and reset the form
- Locale keys added to English and updated throughout the locale files.

## 📸 Screenshots

-   ### Before

image

https://github.com/user-attachments/assets/293739a1-9142-461b-9082-0b3279476e95

-   ### After
Testing locally to show it goes into the DB
image

https://github.com/user-attachments/assets/eaed5c68-31a6-4ced-ac03-0014fc1bb173

### CODE REVIEW

File: components/SubmissionCompleted.vue [hunk 1]
```diff
@@ -14,18 +14,40 @@
...
         <p
-            class="mb-40 text-neutral-600 text-sm font-bold font-sans"
+            class="mb-20 text-center text-neutral-600 text-sm font-bold font-sans"
         >
             {{ $t('thankYouPage.submission') }}
         </p>
-        <NuxtLink
-            class="flex"
-            to="/"
+        <div
```
Comment (ermish) [inline components/SubmissionCompleted.vue:21]: add an id or class to explain what this div is

File: components/SubmissionCompleted.vue [hunk 2]
```diff
@@ -14,18 +14,40 @@
...
+            class="flex flex-col"
         >
             <button
-                class="px-20 py-3 rounded-full bg-currentColor w-96 text-center
+                class="px-20 py-3 rounded-full bg-currentColor max-w-96 text-center
```
Comment (ermish) [inline components/SubmissionCompleted.vue:25]:
```suggestion
                class="px-20 py-3 rounded-full bg-currentColor w-96 text-center
```

File: components/SubmissionForm.vue [hunk 3]
```diff
@@ -1,163 +1,185 @@
...
-                maxlength="30"
-                :placeholder="$t('submitPage.firstName')"
-                @blur="initialValidationCheck(submissionStore.firstName, 'firstName')"
+            <span
+                class="mb-2 text-primary-text text-sm font-normal font-sans"
+            >{{ $t('submitPage.healthcareProfessionalName') }}</span>
+            <p class="flex text-error text-xs font-sans">
+                <span
+                    :class="[
+                        !isValidInput.lastName.value ? 'visible' : 'invisible',
```
Comment (ermish) [inline components/SubmissionForm.vue:44]: I think you can just use v-show or v-if here.
If the page layout messes up, you can have this in a container with a fixed size that doesn't disappear and then just conditionally render the element within.

File: components/SubmissionForm.vue [hunk 4]
```diff
@@ -1,163 +1,185 @@
...
+                        'w-44',
+                        'mr-1',
+                    ]"
+                >
+                    {{ $t('submitPage.lastNameValidation') }}
+                </span>
+                <span
+                    :class="[
```
Comment (ermish) [inline components/SubmissionForm.vue:52]: ♻️

File: components/SubmissionForm.vue [hunk 5]
```diff
@@ -1,163 +1,185 @@
...
-        >
-            <option
-                v-for="(locale, index) in localeStore.localeDisplayOptions"
-                :key="index"
-                selected
-                :value="locale.code"
+                <option
+                    v-for="(locale, index) in localeStore.localeDisplayOptions"
+                    :key="index"
+                    selected
```
Comment (ermish) [inline components/SubmissionForm.vue:103]: double check this. I'm pretty sure this is making EVERY option selected. you might want to just have the first one in the array as selected or have none of them.

File: components/SubmissionForm.vue [hunk 6]
```diff
@@ -1,163 +1,185 @@
...
-             text-primary-inverted font-medium font-sans"
-            @click="validateFields"
-        >
-            {{ $t('submitPage.submitButton') }}
-        </button>
-    </form>
+                {{ $t('submitPage.invalidOption') }}
+            </p>
+            <select
+                v-model="selectLanguage2"
```
Comment (ermish) [inline components/SubmissionForm.vue:119]: future feature: we should be able to support `n` number of languages.

File: components/SubmissionForm.vue [hunk 7]
```diff
@@ -1,163 +1,185 @@
...
+                data-testid="submit-select-language2"
+                class="mb-5 px-3 py-3.5 w-96 h-12 bg-primary-text-inverted rounded-lg border border-primary-text-muted
+                        text-primary-text text-sm font-normal font-sans placeholder-primary-text-muted"
+                :placeholder="$t('submitPage.selectLanguage2')"
+                @change="initialValidationCheck(selectLanguage1, 'secondaryLanguage')"
+            >
+                <option
+                    v-for="(locale, index) in localeStore.localeDisplayOptions"
+                    :key="index"
+                    selected
```
Comment (ermish) [inline components/SubmissionForm.vue:129]: ♻️

File: components/SubmissionForm.vue [hunk 8]
```diff
@@ -198,7 +220,48 @@ const validateFields = (e: Event) => {
         e.preventDefault()
         return
     }
-    submissionStore.submit()
+    submitNewSubmission()
```
Comment (ermish) [inline components/SubmissionForm.vue:223]: should await this function

Comment (ermish) [reply components/SubmissionForm.vue:223]: also, this shouln't be called in validateFields. It should be the other way around where submit should call validateFields.

File: components/SubmissionForm.vue [hunk 9]
```diff
@@ -198,7 +220,48 @@ const validateFields = (e: Event) => {
...
+        googleMapsUrl: location.value,
+        healthcareProfessionalName: `${firstName.value} ${lastName.value}`,
+        spokenLanguages: spokenLanguages,
+        notes: otherNotes.value
+    } }
+
+    const response = await submissionStore.createNewSubmission(newSubmission)
+    if (response?.errors?.length) {
+        response.errors.map(error => {
+            toast.error((t(`serverErrorMessages.${error.extensions.code}`)))
```
Comment (ermish) [inline components/SubmissionForm.vue:248]: should check if the code exists first. The server could have a new one that we haven't supported yet on the front end. In the case where it doesn't exist, we can just send a generic error message to the user and log the error code that was unrecognized.

File: components/SubmissionForm.vue [hunk 10]
```diff
@@ -232,29 +295,38 @@ const initialValidationCheck = async (inputValue: string, field: string) => {
...
     if (validationCheckedPreviously.secondarySpokenLanguage.value) {
         isValidInput.secondarySpokenLanguage.value = validations.validateSecondSpokenLanguage(newValue)
     }
 })
+
+onMounted(async () => {
+    toast = useToast()
+
+    resetForm()
+    await nextTick()
```
Comment (ermish) [inline components/SubmissionForm.vue:328]: should leave comment for people that don't know what this does

File: components/SubmissionForm.vue [hunk 11]
```diff
@@ -232,29 +295,38 @@ const initialValidationCheck = async (inputValue: string, field: string) => {
...
+
+    isSubmissionFormReady.value = true
```
Comment (ermish) [inline components/SubmissionForm.vue:330]: nit: could make this slightly more clear to indicate it's around being loaded or not like `isFormLoaded` or `isFormInitialized`

File: components/SubmissionForm.vue [hunk 12]
```diff
@@ -1,163 +1,185 @@
 <template>
-    <form class="flex flex-col place-self-center">
-        <h1
-            data-testid="submit-heading"
-            class="mb-3.5 text-center text-primary-text text-2xl font-bold font-sans leading-normal"
+    <div>
+        <form
+            v-show="isSubmissionFormReady"
```
Comment (ermish) [inline components/SubmissionForm.vue:4]: should we add a loader for this? (you could test using the chrome debugger tools fake 3g connection and see if the user is waiting on a blank page.

File: stores/submissionStore.ts [hunk 13]
```diff
@@ -1,57 +1,45 @@
...
 import { defineStore } from 'pinia'
-import { ref, type Ref } from 'vue'
-import { gqlClient } from '../utils/graphql.js'
-import type { Locale, CreateSubmissionInput, Submission } from '~/typedefs/gqlTypes'
+import { type Ref, ref } from 'vue'
+import { gqlClient, graphQLClientRequestWithRetry } from '../utils/graphql.js'
+import type { ServerResponse, ErrorCode, ServerErrorResponse } from '~/typedefs/serverResponse.js'
+import type { MutationCreateSubmissionArgs, Submission } from '~/typedefs/gqlTypes'
+
+export interface SubmissionFormInputFields {
```
Comment (ermish) [inline stores/submissionStore.ts:8]: this isn't used. DELETE 🔥 🤖 🔥

File: stores/submissionStore.ts [hunk 14]
```diff
@@ -1,57 +1,45 @@
...
+            response = await graphQLClientRequestWithRetry(
+                gqlClient.request.bind(gqlClient),
+                createSubmissionMutation,
+                newSubmission
+            ) as ServerResponse<Submission>
         } catch (e) {
             console.error(`There was an error creating the submission ${e}`)
+            const ServerErrorResponse = e as ServerErrorResponse
+
+            ServerErrorResponse.response.errors.forEach(errorResponse => {
```
Comment (ermish) [inline stores/submissionStore.ts:29]: It would be more readable if you used a `map()` function and set the response.errors to the new map array. 
Tip:
any time you're changing the shape of an object or iterating through something that you are going to assign to another variable, use `map()`
`forEach()` is better for iterating and doing an action on each item. (like rendering or saving each one)

Comment (ermish) [inline stores/submissionStore.ts:29]: I think this error handling is nice and since we want to do something similar on each request to the server, we should move this into the request method so every request doesn't have to write the same logic

File: typedefs/serverResponse.ts [hunk 15]
```diff
@@ -1,40 +1,29 @@
...
+    locations: ErrorLocation[]
+    extensions: {
+        code: ErrorCode
+    }
 }
 
 export enum ErrorCode {
-    SERVER_ERROR = 'SERVER_ERROR',
-    NOT_FOUND = 'NOT_FOUND',
-    REQUIRED = 'REQUIRED',
```
Comment (ermish) [inline typedefs/serverResponse.ts:16]: why get rid of these? We might as well leave them even if we're not using them

**Review by ermish — CHANGES_REQUESTED** [review]
nice improvements! sugoi!

File: components/SubmissionForm.vue (hunk 12 above)
Comment (NabbeunNabi) [reply components/SubmissionForm.vue:4]: @ermish That is a really cool tool I didn't know about. It is definitely necessary in that case

File: components/SubmissionForm.vue (hunk 5 above)
Comment (NabbeunNabi) [reply components/SubmissionForm.vue:103]: yea it isn't necessary

File: components/ModEditSubmissionForm.vue [hunk 16]
```diff
@@ -803,7 +803,7 @@ async function submitUpdatedSubmission(e: Event) {
     }
     try {
         const result = await moderationSubmissionStore.updateSubmission(submissionInputVariables)
-        const submissionResult = result as { updateSubmission: Submission }
+        const submissionResult = result as unknown as { updateSubmission: Submission }
```
[the remark this answers is not in the document]
Comment (NabbeunNabi) [reply components/ModEditSubmissionForm.vue:806]: @ermish It says because of the generic data type within the function call here I have to convert it to unknown since it uses `T` in the utility function before converting it to its type

File: utils/graphql.ts [hunk 17]
```diff
@@ -24,29 +25,42 @@ export const initializeGqlClient = () => {
...
+
+            // This is a consistent error messaging no matter the type of query or mutation
+            console.error(`There was an error executing the request: ${error}`)
+            const serverError = error as ServerErrorResponse
+
+            // This map transforms errors if they exist
+            const errors = serverError.response?.errors?.map(errorResponse => ({
+                message: errorResponse.message,
+                locations: errorResponse.locations,
+                extensions: { code: errorResponse.extensions.code as ErrorCode }
```
[the remark this answers is not in the document]
Comment (NabbeunNabi) [reply utils/graphql.ts:60]: What do you mean? the map should be called code? Or you saying to change the extensions part to `code`. But this is just replicating the `graphql` error being sent to the frontend

File: components/ModEditSubmissionForm.vue (hunk 16 above)
[the remark this answers is not in the document]
Comment (ermish) [reply components/ModEditSubmissionForm.vue:810]: re-reviewed, for this, look at where we define `T`. You can set constraints for T

**Review by ermish — CHANGES_REQUESTED** [review]
re-reviewed! just the two comments left

File: typedefs/serverResponse.ts [hunk 18]
```diff
@@ -1,13 +1,26 @@
...
+
+export type ErrorLocation = {
+    line: number
+    column: number
+}
+
+export type ServerError = {
+    message: string
+    locations: ErrorLocation[]
+    extensions: {
```
Comment (ermish) [inline typedefs/serverResponse.ts:21]: let's remove extensions and just have `code`

File: utils/graphql.ts (hunk 17 above)
[the remark this answers is not in the document]
Comment (NabbeunNabi) [reply utils/graphql.ts:60]: I think I did it

**Comment by NabbeunNabi** [comment]
@ermish Figured out the types and also made a utility function since we want error messaging to be shown that can be reused since our messages is going to come from the server

File: components/ModEditSubmissionForm.vue [hunk 19]
```diff
@@ -805,18 +808,20 @@ async function submitUpdatedSubmission(e: Event) {
...
-        toast.success(t('modSubmissionForm.successMessageUpdated'))
-        if (moderationSubmissionStore.updatingSubmissionFromTopBar) {
-            router.push('/moderation')
-            moderationSubmissionStore.setUpdatingSubmissionFromTopBar(false)
-        }
-    } catch {
-        toast.error(t('modSubmissionForm.errorMessageUpdated'))
+
+    const result = await moderationSubmissionStore.updateSubmission(submissionInputVariables)
+    const submissionResult = result as ServerResponse<Mutation>
```
Comment (ermish) [inline components/ModEditSubmissionForm.vue:813]: let's set this as  a  return type of the `updateSubmission()`  function so the caller doesn't have to  set and figure out the types each time

Comment (NabbeunNabi) [reply components/ModEditSubmissionForm.vue:813]: So `updateSubmission` is `Maybe<Submission>` so I will set it to `Submission` as the errors will be caught in the following part

File: stores/moderationSubmissionsStore.ts [hunk 20]
```diff
@@ -85,18 +87,25 @@ export const useModerationSubmissionsStore = defineStore(
...
+            if (response.errors?.length) {
                 setDidMutationFail(true)
                 setUpdatingSubmissionFromTopBar(false)
             }
+
+            serverResponse.data = response.data?.updateSubmission
+            serverResponse.errors = response.errors ? response.errors : []
+            serverResponse.hasErrors = response.hasErrors
+
+            return serverResponse
```
Comment (NabbeunNabi) [inline stores/moderationSubmissionsStore.ts:108]: @ermish I had to change the way the function was written in order to show what type of mutation it was. And make a new object to send since we do a Mutation, and get back the type of updateSubmission. But the api call doesn't work this way. They can sese that it is updateSubmission on line 104. But their isn't really a way to access the key since the key as a type that I can see as that causes a mismatch of what we get

Comment (NabbeunNabi) [reply stores/moderationSubmissionsStore.ts:108]: If I try to specify the type I get this
image
From trying the following code

```

        async function updateSubmission(submission: MutationUpdateSubmissionArgs):
        Promise<ServerResponse<Mutation['updateSubmission']>> {
            const response = await graphQLClientRequestWithRetry<Mutation['updateSubmission']>(
                gqlClient.request.bind(gqlClient),
                updateFacilitySubmissionGqlMutation,
                submission
            )

            if (response.errors?.length) {
                setDidMutationFail(true)
                setUpdatingSubmissionFromTopBar(false)
            }

            return response
        }
        ```

Comment (NabbeunNabi) [reply stores/moderationSubmissionsStore.ts:108]: I then cannot access this key due to typing

File: utils/handleServerErrorMessaging.ts [hunk 21]
```diff
@@ -0,0 +1,18 @@
+import type { ToastInterface } from 'vue-toastification'
+import type { ServerError } from '~/typedefs/serverResponse'
+
+export function handleServerErrorMessaging(
```
Comment (ermish) [inline utils/handleServerErrorMessaging.ts:4]: nit: you could put this in the graphql file since I don't think it'll be used outside of it

File: components/ModEditSubmissionForm.vue [hunk 22]
```diff
@@ -805,18 +806,21 @@ async function submitUpdatedSubmission(e: Event) {
...
+    const result = await moderationSubmissionStore.updateSubmission(submissionInputVariables)
+    // This is used in the component and not graphQL call as it is user messaging and needs the mounted toast library
+    if (result?.errors?.length) {
+        handleServerErrorMessaging(result.errors, toast, t)
+        return
+    }
+
+    const submissionResult = result.data
+    // This updates the submission in the form with the values stored in the db on success
+    if (submissionResult) initializeSubmissionFormValues(submissionResult)
```
Comment (ermish) [inline components/ModEditSubmissionForm.vue:819]: this looks cleaner now! nice work

File: stores/moderationSubmissionsStore.ts (hunk 20 above)
Comment (ermish) [reply stores/moderationSubmissionsStore.ts:108]: you've done some good research on typing  😸  this is honestly an issue in pretty much every typed language. 

My advice at this point is it's more hassle to make it work for the nested Mutation type. (hence why it's not on the server side) 
I think it's fine to cast when accessing the inner object in the <mutation>, but the <serverResponse> and <Mutation> should at least be in the function's return type. So basically, `Promise<ServerResponse<Mutation>>` is good 👍 

Looking at what you got above, I think that is ideal ✨

**Review by ermish — APPROVED** [review]
woo! nice work updating through the changes and getting this through

File: utils/handleServerErrorMessaging.ts (hunk 21 above)
Comment (NabbeunNabi) [reply utils/handleServerErrorMessaging.ts:4]: Due to toast being accessed on build and also translation not be available. We talked about this. This can be addressed in a future issue if we can figure out a better way to load toasts not on mount and have translations available outside of the components.
