### PR TITLE
fix: add accessible themes

### LINKED ISSUE #1041: Create accessible theme for high contrast
# Problem
We are an app that wants to help those find access to healthcare so we should improve our themes to have a high contrast accessibility theme in our `tailwind.css` file.

# Success
The color scheme and implementation of a high contrast theme is researched and added to our [`tailwind.css` file](https://github.com/ourjapanlife/findadoc-web/blob/main/assets/css/tailwind.css)

### Requirements

- [ ] Research high contrast accessibility themes
- [ ] Add a theme consistent with our codebases naming conventions in the file linked above

# Implementation notes
Here are some articles on high contrast mode:
- https://assistivlabs.com/assistive-tech/display/high-contrast-mode
- https://dev.to/ingosteinke/add-a-high-contrast-theme-toggle-to-a-pastel-website-4kjn

### PR DESCRIPTION
**Pull request by sylentwulf81**
✅ Resolves #1041 
- [x] PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specifications
- [x] PR assignee has been selected
- [x] PR label has been selected
- [x] @NabbeunNabi has been selected for preliminary review

## 🔧 What changed

Added 'high contrast' and 'color blind: daltonism (red green colorblindness)' themes to theme selector. 

Theme selector now displays theme title upon user selection.

## 🧪 Testing instructions

1. Reduce size of viewing window to 'less than 1080p' to enable 'hamburger' menu. 
2. Click 'humburger' menu to display settings and theme selector
3. Select theme of choice

## 📸 Screenshots

-   ### Before

adds-accessible-themes-before

-   ### After

Screenshot 2025-05-18 at 12 27 28 PM
Screenshot 2025-05-18 at 12 27 14 PM

### CODE REVIEW

**Comment by NabbeunNabi** [comment]
@sylentwulf81 Great work on this so far. Just a few things.

You will want to 

1. Run `yarn lint:fix` locally in order to pass the linter or find the problems where you have the CI/CD failing as it is here 
image
2. Same as the above picture you want to make sure that your PR title has conventional commits. Since on this codebase we squash and merge commits the actual commits become the body and the PR title itself becomes the commit message. This is important for cleanliness and makes it easy to see the history of commits
3. You want to click this inputs once you have finished all the parts of them as a checklist. I color coded a picture
image
4. Also in the above picture is the pink. This is not always necessary, but since your PR includes a UI change you should include screenshots. It is quicker for us to read the code and see a UI change than to have to checkout to branch and run the whole server

File: components/HamburgerMenu.vue [hunk 1]
```diff
@@ -141,30 +141,49 @@
...
+                                :class="getSelectedTheme('accessible-high-contrast')"
+                                @click="setTheme('accessible-high-contrast')"
+                                title="Accessible: High Contrast Theme"
+                            />
+                            <div
+                                class="w-10 h-10 mr-1"
+                                style="background-color: #FF0000FF;"
+                                :class="getSelectedTheme('accessible-red-green')"
+                                @click="setTheme('accessible-red-green')"
+                                title="Accessible: Daltonian Color Blindness"
```
Comment (NabbeunNabi) [inline components/HamburgerMenu.vue:186]: This goes for all of them @sylentwulf81. The on hover works when testing on desktop. I do not think they are bad to have. But when it come to a phone as you can scan in the mobile preview. Is there a way to add a touch hover effect with tailwind or vue? Because there is no hover on most mobile device unless they use the apple pen and when it is close etc.

File: components/HamburgerMenu.vue [hunk 2]
```diff
@@ -285,7 +304,7 @@ function logout() {
 }
 
 function setTheme(newTheme: string) {
-    document.documentElement.classList.remove('theme-orange', 'theme-coral', 'theme-violet', 'theme-ocean', 'theme-neon')
+    document.documentElement.classList.remove('theme-orange', 'theme-coral', 'theme-violet', 'theme-ocean', 'theme-neon', 'theme-accessible-high-contrast', 'theme-accessible-red-green')
```
Comment (NabbeunNabi) [inline components/HamburgerMenu.vue:307]: Just by looking at this I think it might be longer than the text limit we set on the linter on the line.

File: components/HamburgerMenu.vue [hunk 3]
```diff
@@ -141,30 +141,49 @@
...
                                 @click="setTheme('ocean')"
+                                title="Ocean Theme"
                             />
                             <div
-                                class="w-10 h-10"
+                                class="w-10 h-10 mr-1"
                                 style="background-color: #1bdb9b;"
                                 :class="getSelectedTheme('neon')"
                                 @click="setTheme('neon')"
+                                title="Neon Theme"
```
Comment (NabbeunNabi) [inline components/HamburgerMenu.vue:172]: You might need to move the `title` attribute higher. We have some stylistic attributes that will throw errors. `EsLint` extension should show all of this if you have it running.

File: components/HamburgerMenu.vue (hunk 2 above)
Comment (sylentwulf81) [reply components/HamburgerMenu.vue:307]: fixed in upcoming commit

File: components/HamburgerMenu.vue (hunk 3 above)
Comment (sylentwulf81) [reply components/HamburgerMenu.vue:172]: fixed in upcoming commit

**Comment by sylentwulf81** [comment]
Requested changes have been made.

File: components/HamburgerMenu.vue (hunk 1 above)
Comment (sylentwulf81) [reply components/HamburgerMenu.vue]: Currently this has been solved by adding an alert when the user taps and holds. Ideally I'd like to use the existing vue-toastification implementation to present the information to the user instead, but that will take some time and may be better added as a disparate issue, since it feels like I might be going somewhat off-scope for this particular issue.

Comment (ermish) [reply components/HamburgerMenu.vue]: Two thoughts:
1 what's the use case for the ping touch? I'm wondering if users would even find this or need the feature. Not opposed and it's cool, just thinking through the UX flow 🤔
2 I'm nervous about committing an alert as we reeeeally shouldn't use them unless it's a critical page error. Do we have an open issue to switch this to a toast if we keep it?

Comment (NabbeunNabi) [reply components/HamburgerMenu.vue]: 👍  agree toast over alert

Comment (sylentwulf81) [reply components/HamburgerMenu.vue]: @NabbeunNabi do you know the answer to @ermish's question by chance? If there's an issue to add toasts, I can attach that and work on it here || I can take out the alerts and push the themes as is. As mentioned previously, my concerns are over scoping and historicity.

Comment (NabbeunNabi) [reply components/HamburgerMenu.vue]: There is not an issue.

So what I would suggest is...taking out the alerts in this one.

Writing an issue through the board with our template and following other ones you see to add toasts for changing. And do it in a separate PR.

And when you have time we can do some rebasing to clean up the commit history within this PR

Comment (sylentwulf81) [reply components/HamburgerMenu.vue]: Doing so now.

Comment (sylentwulf81) [reply components/HamburgerMenu.vue]: > There is not an issue.
> 
> So what I would suggest is...taking out the alerts in this one.
> 
> Writing an issue through the board with our template and following other ones you see to add toasts for changing. And do it in a separate PR.
> 
> And when you have time we can do some rebasing to clean up the commit history within this PR

Requested changes have been made.

File: components/HamburgerMenu.vue [hunk 4]
```diff
@@ -307,7 +336,12 @@ onMounted(() => {
     }
 })
 
-//this is a custom directive to close the menu when clicking outside of the menu
+// converts the theme name to locale case (first letter uppercase, rest lowercase)
+function toLocaleCase(theme: string) {
```
Comment (ermish) [inline components/HamburgerMenu.vue:340]: I think this should be Pascal Case instead of Locale
```suggestion
function toPascalCase(theme: string) {
```

Also, this would likely be a great additon to move into our utils so it can be reused 😸

File: components/HamburgerMenu.vue [hunk 5]
```diff
@@ -307,7 +336,12 @@ onMounted(() => {
...
+    return theme.charAt(0).toUpperCase() + theme.slice(1)
```
Comment (ermish) [inline components/HamburgerMenu.vue:341]: let's add a check in here to make sure the string isn't empty/undefined otherwise `charAt()` and could throw an exception

File: components/HamburgerMenu.vue [hunk 6]
```diff
@@ -285,13 +306,21 @@ function logout() {
...
+        'theme-accessible-high-contrast',
+        'theme-accessible-red-green'
+    )
     document.documentElement.classList.add(`theme-${newTheme}`)
     localStorage.setItem('theme', newTheme)
     currentTheme.value = newTheme
 }
 
-// this gives a black border to the selected theme in the hamburger menu
+// this gives a black border to the selected theme in the hamburger menu (mobile view)
```
Comment (ermish) [inline components/HamburgerMenu.vue:323]: there's a chance the desktop won't be using a hamburger menu, so we might not need this 🤔

**Review by ermish — CHANGES_REQUESTED** [review]
looking good! some small comments, then it's ready to go!

File: components/HamburgerMenu.vue (hunk 4 above)
Comment (sylentwulf81) [reply components/HamburgerMenu.vue:340]: moved to stringUtils.ts and renamed in forthcoming commit.

File: components/HamburgerMenu.vue (hunk 6 above)
Comment (sylentwulf81) [reply components/HamburgerMenu.vue:323]: Suggest leaving it for now until we know one way or the other?

File: components/HamburgerMenu.vue (hunk 5 above)
Comment (sylentwulf81) [reply components/HamburgerMenu.vue]: check added in forthcoming commit.

**Comment by sylentwulf81** [comment]
Requested changes have been made.

File: components/HamburgerMenu.vue (hunk 6 above)
Comment (NabbeunNabi) [reply components/HamburgerMenu.vue:324]: By default the hamburger menus are used on mobile devices.

so you can take it out as developers will know it is for mobile. If it does end up being used on desktop then the comment is still appropriate.

if not we have to fix the comment later.

so I would just remove that but 😄

**Review by ermish — COMMENTED** [review]
few small comments here, otherwise looks good!

File: components/HamburgerMenu.vue (hunk 4 above)
Comment (ermish) [reply components/HamburgerMenu.vue]: oof, you're right! I think I mean't Sentencecase, not PascalCase 😆  this looks good now 👍

File: utils/stringUtils.ts [hunk 7]
```diff
@@ -50,3 +50,12 @@ export function isValidUrl(url: string | URL) {
     }
     return url.protocol === 'https:'
 }
+
+// converts the theme name to locale case (first letter uppercase, rest lowercase)
+export function toLocaleCapitalized(theme: string) {
+    if (theme.length === 0) { // if the string is empty, return an empty string
+        return ''
+    } else {
```
[the remark this answers is not in the document]
Comment (sylentwulf81) [reply utils/stringUtils.ts:58]: Dang, great callout, thank you.

File: components/HamburgerMenu.vue (hunk 2 above)
Comment (sylentwulf81) [reply components/HamburgerMenu.vue]: Requested changes have been made.

File: components/HamburgerMenu.vue (hunk 3 above)
Comment (sylentwulf81) [reply components/HamburgerMenu.vue]: Requested changes have been made.

File: components/HamburgerMenu.vue (hunk 6 above)
Comment (sylentwulf81) [reply components/HamburgerMenu.vue:324]: Requested changes have been made.

File: utils/stringUtils.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (sylentwulf81) [reply utils/stringUtils.ts:58]: Fixed in upcoming commit.

[the remark this answers is not in the document]
Comment (sylentwulf81) [reply utils/stringUtils.ts]: Requested changes have been made.

**Review by NabbeunNabi — APPROVED** [review]
Great job rebasing! @ermish over to you

**Review by NabbeunNabi — APPROVED** [review]

**Review by ermish — APPROVED** [review]
looks great @sylentwulf81! nice work!

File: assets/css/tailwind.css [hunk 8]
```diff
@@ -121,4 +121,52 @@
     --color-bg-tertiary: /* #e5e7eb */ 82 82 82;
     --color-error: /* #525252 */ 209 82 63;
   }
+
+    /* MARK: Accessible Themes */
+
+/* accessible high contrast theme */
+ /* sses black/white backgrounds and text with bright accents */
```
Comment (theyokohamalife) [inline assets/css/tailwind.css:128]: I'm not sure what "sses" means in this context. 😅

File: utils/stringUtils.ts [hunk 9]
```diff
@@ -50,3 +50,9 @@ export function isValidUrl(url: string | URL) {
     }
     return url.protocol === 'https:'
 }
+
+// converts the theme name to sentence case
+export function toSentenceCase(theme: string) {
```
Comment (theyokohamalife) [inline utils/stringUtils.ts:55]: We can remove this comment if we make the function name more explicit.

```suggestion
export function convertThemeNameToSentenceCase(theme: string) {
```

File: components/HamburgerMenu.vue [hunk 10]
```diff
@@ -286,13 +308,21 @@ function logout() {
...
+        'theme-accessible-high-contrast',
+        'theme-accessible-red-green'
+    )
     document.documentElement.classList.add(`theme-${newTheme}`)
     localStorage.setItem('theme', newTheme)
     currentTheme.value = newTheme
 }
 
-// this gives a black border to the selected theme in the hamburger menu
+// this gives a black border to the currently selected theme
```
Comment (theyokohamalife) [inline components/HamburgerMenu.vue:325]:
```suggestion
// This gives a black border to the currently selected theme
```

I know this comment was lowercase before you made changes, but it's good to fix it while we're at it.

File: utils/stringUtils.ts [hunk 11]
```diff
@@ -50,3 +50,9 @@ export function isValidUrl(url: string | URL) {
...
+    // if the string is empty, return an empty string, otherwise capitalize the first letter and lowercase the rest
```
Comment (theyokohamalife) [inline utils/stringUtils.ts:56]:
```suggestion
```

I think it's safe to leave this comment out.

**Review by theyokohamalife — CHANGES_REQUESTED** [review]
Looking forward to having more accessible themes! Left a couple suggestions, but also have a question about the theme name that is displayed to users. Did we intend for the names to be hyphenated like this? @NabbeunNabi @ermish 

Screenshot 2025-05-17 at 1 38 33 PM

Based on the `alt` text that you introduced, I think maybe it was intended to show as "Theme: Accessible High Contrast"?

File: assets/css/tailwind.css (hunk 8 above)
Comment (sylentwulf81) [reply assets/css/tailwind.css:128]: Seems like a typo but I'm not sure what I could have been typing that would have led to that. I can push these explanations into our branding guidelines and clean this up, though!

File: components/HamburgerMenu.vue (hunk 10 above)
Comment (sylentwulf81) [reply components/HamburgerMenu.vue:325]: ah, bad habit, will fix this in upcoming commit.

**Comment by sylentwulf81** [comment]
Hyphens being displayed to the user is definitely an oversight. Fixing now.

File: assets/css/tailwind.css (hunk 8 above)
Comment (sylentwulf81) [reply assets/css/tailwind.css:128]: On review I think it was supposed to be "uses", but the comment is superfluous.

File: components/HamburgerMenu.vue (hunk 10 above)
Comment (sylentwulf81) [reply components/HamburgerMenu.vue:325]: Fixed in upcoming commit.

File: utils/stringUtils.ts [hunk 12]
```diff
@@ -50,3 +50,24 @@ export function isValidUrl(url: string | URL) {
...
+// converts a given string into "Title Case"
+export function convertStringToTitleCase(stringToConvert: string) {
+    // if we don't have a string to convert, return
+    if (!stringToConvert) {
+        return ''
+    }
+    const normalizedString = stringToConvert.replace(/[^a-zA-Z0-9]+/g, ' ').trim()
+    const splitStringArray = normalizedString.split(' ')
+
+    // capitalize each word using helper function
```
Comment (theyokohamalife) [inline utils/stringUtils.ts:69]: Looking good! Let's remove the comments since it's much clearer what the functions are doing with their new names.

Comment (sylentwulf81) [reply utils/stringUtils.ts]: Apologies for the delay. Requested changes have been made.

**Comment by sylentwulf81** [comment]
@NabbeunNabi I still have no idea why my VS Code on Mac auto-formats things, I have every possible selector I could find that has anything to do with formatting turned off or uninstalled. I may need you to clean up the linter errors and resubmit as you did previously.

**Comment by NabbeunNabi** [comment]
@sylentwulf81 have you implemented the changes necessary for @theyokohamalife? Just curious. Do not feel pressured. Just trying to get some status updates. If you have do not forget to click re request

**Comment by sylentwulf81** [comment]
Requested changes have been made.

**Comment by sylentwulf81** [comment]
I didn't create those so I was hesitant to comment, but the first three themes are basically identical other than text color. The "Ocean" theme doesn't really sing "ocean" colors to me but that was beyond the scope of what I was adding, so I figured I'd address it in a separate issue later.

For me themes should be both different enough to warrant inclusion and aesthetically obvious enough to present clearly to the user. As of right now the only additional themes outside of the base colorway that meets these criteria are Neon, Accessible Daltonism and Accessible High Contrast. The rest aren't visually disparate enough to warrant inclusion, in my opinion. 

Again I want to highlight this isn't a commentary on anyone's work or design decisions - just my thoughts as a pair of fresh eyes.

**Comment by ermish** [comment]
@theyokohamalife I checked and the ocean theme was broken from an unrelated PR which we can fix in a separate issue. Can you take another look at this when you have a chance?

**Review by theyokohamalife — APPROVED** [review]
Thank you for making our platform more accessible!

**Comment by theyokohamalife** [comment]
> @theyokohamalife I checked and the ocean theme was broken from an unrelated PR which we can fix in a separate issue. Can you take another look at this when you have a chance?

@ermish  Can we make sure that an issue is created that includes info on how it was broken? 🙏🏾
