### PR TITLE
FIX: Change styling values using our Tailwind classes

### LINKED ISSUE #546: BUG: fix hard coded colors
# Problem
We have a color theme for our site and nice tailwind selectors to ensure consistency. In addition, our themes can be changed by the user if we don't hard code color choices. 

We'll want to follow this to ensure we can add accessibility color / font options later. 

# Success
- look for any hard coded colors 
  - ex. `border-zinc-400` -> `border-secondary` or `border-primary-text-muted`.  
  -  ex. `bg-white`, `text-white`, etc. 
- if time permits, try to shift hard coded font sizes, font families, etc. to tailwind style ex `font-['Noto Sans JP']` can be `font-sans`

### PR DESCRIPTION
**Pull request by Anissa3005**
Resolves #546 

## 🔧 What changed

- Before some styling classes contained hard coded colors, I have changed them to our set class colors
- Before some styling classes contained px values I have changed them to the Tailwind standards

### CODE REVIEW

File: components/SubmissionForm.vue [hunk 1]
```diff
@@ -26,25 +26,25 @@
...
             {{ $t('submitPage.lastNameValidation') }}
         </p>
         <div>
             <input
                 v-model="submissionStore.lastName"
                 data-testid="submit-input-lastname"
-                class="mb-5 mr-2 px-3 py-3.5 w-[170px] h-[50px] bg-white rounded-lg border border-zinc-400
-            text-neutral-600 text-sm font-normal font-['Noto Sans JP']"
+                class="mb-5 mr-1 px-3 py-3.5 w-48 h-12 bg-white rounded-lg border border-primary-text-muted
+            text-primary-text text-sm font-normal font-sans placeholder-primar"
```
Comment (ermish) [inline components/SubmissionForm.vue:47]: misspell

File: components/SubmissionForm.vue [hunk 2]
```diff
@@ -26,25 +26,25 @@
             data-testid="submit-input-googlemaps"
             type="text"
             required
-            class="mb-5 px-3 py-3.5 w-[350px] h-[50px] bg-white rounded-lg border border-zinc-400
-          text-neutral-600 text-sm font-normal font-['Noto Sans JP']"
+            class="mb-5 px-3 py-3.5 w-96 h-12 bg-white rounded-lg border border-primary-text-muted
+            text-primary-text text-sm font-normal font-sans placeholder-primar"
```
Comment (ermish) [inline components/SubmissionForm.vue:30]: misspell
```suggestion
            text-primary-text text-sm font-normal font-sans placeholder-primary"
```

File: components/SubmissionForm.vue [hunk 3]
```diff
@@ -53,26 +53,27 @@
             <input
                 v-model="submissionStore.firstName"
                 data-testid="submit-input-firstname"
-                class="mb-5 px-3 py-3.5 w-[170px] h-[50px] bg-white rounded-lg border border-zinc-400
-            text-neutral-600 text-sm font-normal font-['Noto Sans JP']"
+                class="mb-5 px-3 py-3.5 w-48 h-12 bg-white rounded-lg border border-primary-text-muted
+            text-primary-text text-sm font-normal font-sans placeholder-primar"
```
Comment (ermish) [inline components/SubmissionForm.vue:57]: ♻️

File: components/SubmissionForm.vue [hunk 4]
```diff
@@ -26,25 +26,25 @@
             data-testid="submit-input-googlemaps"
             type="text"
             required
-            class="mb-5 px-3 py-3.5 w-[350px] h-[50px] bg-white rounded-lg border border-zinc-400
-          text-neutral-600 text-sm font-normal font-['Noto Sans JP']"
+            class="mb-5 px-3 py-3.5 w-96 h-12 bg-white rounded-lg border border-primary-text-muted
```
Comment (ermish) [inline components/SubmissionForm.vue:29]: instead of `bg-white` try one of the theme colors.

File: components/SubmissionForm.vue [hunk 5]
```diff
@@ -53,26 +53,27 @@
             <input
                 v-model="submissionStore.firstName"
                 data-testid="submit-input-firstname"
-                class="mb-5 px-3 py-3.5 w-[170px] h-[50px] bg-white rounded-lg border border-zinc-400
-            text-neutral-600 text-sm font-normal font-['Noto Sans JP']"
+                class="mb-5 px-3 py-3.5 w-48 h-12 bg-white rounded-lg border border-primary-text-muted
```
Comment (ermish) [inline components/SubmissionForm.vue:56]: ♻️

File: components/SubmissionForm.vue [hunk 6]
```diff
@@ -53,26 +53,27 @@
...
-            class="text-currentColor text-xs font-['Noto Sans JP']"
+            class="text-currentColor text-xs font-sans"
         >
             {{ $t('submitPage.spokenLanguageValidation') }}
         </p>
         <select
             v-model="submissionStore.selectLanguage1"
             data-testid="submit-select-language1"
-            class="mb-5 px-3 py-3.5 w-[350px] h-[50px] bg-white rounded-lg border border-zinc-400 text-primary-text"
+            class="mb-5 px-3 py-3.5 w-96 h-12 bg-white rounded-lg border border-primary-text-muted
```
Comment (ermish) [inline components/SubmissionForm.vue:75]: ♻️

File: components/SubmissionForm.vue [hunk 7]
```diff
@@ -85,18 +86,19 @@
...
-            class="text-currentColor text-xs font-['Noto Sans JP']"
+            class="text-currentColor text-xs font-sans"
         >
             {{ $t('submitPage.invalidOption') }}
         </p>
         <select
             v-model="submissionStore.selectLanguage2"
             data-testid="submit-select-language2"
-            class="mb-5 px-3 py-3.5 w-[350px] h-[50px] bg-white rounded-lg border border-zinc-400 text-primary-text"
+            class="mb-5 px-3 py-3.5 w-96 h-12 bg-white rounded-lg border border-primary-text-muted
```
Comment (ermish) [inline components/SubmissionForm.vue:100]: ♻️

File: pages/terms.vue [hunk 8]
```diff
@@ -2,113 +2,113 @@
...
         <div>
             <h1
-                class="mb-20 text-black text-5xl font-bold font-['Noto Sans JP']"
+                class="mb-20 text-primary-text text-5xl font-bold font-sans"
             >
                 Terms and Conditions
             </h1>
             <p
-                class="mb-10 text-rose-400 text-3xl font-bold font-['Noto Sans JP']"
+                class="mb-10 text-rose-400 text-3xl font-bold font-sans"
```
Comment (ermish) [inline pages/terms.vue:10]: You should update these colors as well. I think this could be either the muted color or you could do an opacity change like `text-primary/40`

**Review by ermish — CHANGES_REQUESTED** [review]
thanks for helping clean up the code!

File: components/SubmissionForm.vue (hunk 4 above)
Comment (Anissa3005) [reply components/SubmissionForm.vue:29]: We don't have a bg color in our theme that is white, but we do have `primary-text-inverted` the only thing is maybe it's confusing because of the name? I can make a new bg theme color as well?

The bg-white was based on the tailwind config file.

File: pages/terms.vue (hunk 8 above)
Comment (Anissa3005) [reply pages/terms.vue:10]: The muted is a bit to light compared to the design (on how is is now), I implemented `text-primary-text/55` and it's still not gray but I think using black makes everything more consistent (we use black as text in other components).

image

File: components/SubmissionForm.vue (hunk 4 above)
Comment (ermish) [reply components/SubmissionForm.vue:29]: https://github.com/ourjapanlife/findadoc-web/blob/ermish/backup-loginform/components/LoginForm.vue

Take a look at what i did for these login form backgrounds that are similar. I used bg-secondary
You can add a new one, but make sure it fits with the theme. When playing with colors, I recommend try adding `theme-neon` to the top div in the app vue file to see if it looks nice on darker themes (I plan to release a dark theme eventually so it's good to test against it)

Comment (Anissa3005) [reply components/SubmissionForm.vue:29]: the secondary-bg is a coral color, like this:

image

Comment (ermish) [reply components/SubmissionForm.vue:29]: Up to you! You can use any of them or add a new one 👍 but make sure to add it across the themes if you add one 🙃

Comment (ermish) [reply components/SubmissionForm.vue:29]: I think by-primary-bg is another color option. You can always just check the ones available in our css file with the theme colors

File: assets/css/tailwind.css [hunk 9]
```diff
@@ -41,7 +41,8 @@
     --color-text-muted: /* #999999 */ 153 153 153;
     --color-text-inverted: /* #ffffff */ 255 255 255;
     --color-bg-primary: /* #FCFCFC */ 252 252 252;
-    --color-bg-secondary: /* #FFF1EF */ 255 241 240;
+    --color-bg-secondary: /* #ffffff */ 255 255 255;
+    --color-bg-tertiary: /* #e5e7eb */ 229 231 235;
```
Comment (Anissa3005) [inline assets/css/tailwind.css:45]: I have add a new bg color, this is for the moderation panel since I notice that for some components we have a gray background color. I'm not sure if this is the best approach, let me know what your opinion is.

**Review by ermish — APPROVED** [review]
looks great! nice work and happy to have the themes upgraded!
