### PR TITLE
fix: doctor website link functionality

### LINKED ISSUE #1244: Fix website for doctor link to be clickable in a new tab
# Problem
Currently when looking at a healthcare professional's information there is no way to click on the website. It does not look like a hyperlink and is not working correctly. For UX we should make it easy for them to click on the website and have it open a new tab. If you inspect the element it shows the tab but you cannot in fact click the link

# Success
The healthcare professional's website if present is a hyperlink that opens a new tab with the styling of a hyperlink for the user.
### Requirements

- [x] Fix hyperlink for healthcare professional's website when available
- [x] hyperlink opens the website when present in a new tab
- [x] The link is stylized so people can understand that it is a clickable link

# Implementation notes

Image

As you can see it shows but you cannot in fact click the hyperlink to go to the website unless you are in the developers console

### PR DESCRIPTION
**Pull request by ConwayDecker**
✅ Resolves #1244 
- [X] PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specifications
- [X] PR assignee has been selected
- [X] PR label has been selected
- [X] @NabbeunNabi has been selected for preliminary review

## 🔧 What changed
- A `preventDefault` in closeOnOutsideClick.ts ha been removed; this is what was preventing the doctor link to work correctly.
- Attributes which allow the link to open in a new tab, provide a bit of security, and styling so it looks like a clickable link.
## 🧪 Testing instructions
Click on the links in the modal.
## 📸 Screenshots

-   ### Before
image
-   ### After
image

### CODE REVIEW

File: utils/closeOnOutsideClick.ts [hunk 1]
```diff
@@ -9,7 +9,6 @@ export const vCloseOnOutsideClick = {
         let isOpen = false
 
         el.clickOutsideEvent = event => {
-            event.preventDefault()
```
Comment (NabbeunNabi) [inline utils/closeOnOutsideClick.ts:12]: This makes sense as to why it would have not been working. Did you make sure this does not affect anything else going on with the modal or hamburger menu? @ConwayDecker

Comment (ConwayDecker) [reply utils/closeOnOutsideClick.ts:12]: I checked out the modal and hamburger menu on both main and this branch; it looks like everything works! Moreover, I found a bug in the hamburger menu "Contact" link since that was being blocked on main.
Now everything seems to work as intended on this branch!

**Review by NabbeunNabi — APPROVED** [review]
Looks great then!

@ermish

**Comment by NabbeunNabi** [comment]
@ConwayDecker I would do some research on UI/UX. I think for now it is probably to go back to the blue underline as that is what users are used to and expect for hyperlinks

**Review by theyokohamalife — APPROVED** [review]
LGTM!

**Review by NabbeunNabi — CHANGES_REQUESTED** [review]
Sorry. Maybe I wasn't clear,
It should always be underlined. Whether hovered or not

**Review by ermish — APPROVED** [review]
looks good! 
After merging, let's double check the modal clickoutside still works 👍
