### PR TITLE
fix: declare $t to resolve incorrect TypeScript error message for translatable strings

### LINKED ISSUE #1252: translatable string $t showing incorrect ts error message
# Problem

Image

The translatable strings ( $t ) have started showing a typescript error message "__VLS_ctx.$t' is of type 'unknown". It is showing up for every instance of $t in the components of findadoc-web. This error should not be showing up, and this needs to be fixed

# Success

This message does not appear for every instance of $t 

### Requirements

- [ ] This error message does not show up for every instance of $t
- [ ] PR has screenshots and proof that this is the case

# Implementation notes

### PR DESCRIPTION
**Pull request by bnogimauemura**
✅ Resolves #1252 
- [x] PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specifications
- [x] PR assignee has been selected
- [x] PR label has been selected
- [x] @NabbeunNabi has been selected for preliminary review

## 🔧 What changed
Declared the $t property in global.d.ts to fix the type error shown in components

Reason: Vue and TypeScript don't recognize the `$t` property by default, which causes a type error `'__VLS_ctx.$t' is of type 'unknown'` .  
I used `Composer['t']` because it's a translation function provided by Vue I18n. By declaring `$t` as `Composer['t']`, every `$t` property used in Vue components will be recognized by TypeScript as the translation function. 

## 📸 Screenshots

-   ### Before
448812882-1a000306-5840-4938-b098-e252acce3cc0

-   ### After
Screenshot 2025-06-10 at 16 34 37

Screenshot 2025-06-10 at 16 32 04

### CODE REVIEW

File: components/Footer.vue [hunk 1]
```diff
@@ -9,26 +9,26 @@
...
-                Date().getUTCFullYear() }} {{ $t('footer.copyright') }}</NuxtLink>
+                Date().getUTCFullYear() }} {{ t('footer.copyright') }}</NuxtLink>
             <span class="self-center">·</span>
             <nav class="flex mx-2">
                 <NuxtLink
                     to="/privacypolicy"
                     class="self-center hover:text-primary-hover transition-colors"
                     data-testid="privacy-link"
-                >{{ $t('footer.privacy') }}</NuxtLink>
+                >{{ ('footer.privacy') }}</NuxtLink>
```
Comment (NabbeunNabi) [inline components/Footer.vue:19]: Missing t

**Review by NabbeunNabi — CHANGES_REQUESTED** [review]
